import React,{useEffect,useState} from 'react';
import {Copy,Eye,Users,UserCheck,DollarSign,LogOut} from 'lucide-react';
import {representativeService} from '../../services/representativeService';
export function RepresentativeDashboard({onLogout}:{onLogout:()=>void}){
 const [d,setD]=useState<any>(null); const [copied,setCopied]=useState(false);
 useEffect(()=>{representativeService.dashboard().then(setD).catch(()=>setD(false));},[]);
 if(!d)return <div className="min-h-screen grid place-items-center bg-[#f7faf8] text-[#12382c]">{d===false?'Não foi possível carregar o painel.':'Carregando...'}</div>;
 const link=`${location.origin}/representante/${d.slug}`;
 const copy=async()=>{await navigator.clipboard.writeText(link);setCopied(true);setTimeout(()=>setCopied(false),1600)};
 const cards=[['Views',d.views,Eye],['Cadastros',d.leads,Users],['Clientes assinados',d.clients,UserCheck],['Comissão','R$ '+Number(d.commissionTotal||0).toFixed(2).replace('.',','),DollarSign]];
 return <div className="min-h-screen bg-[#f7faf8] text-[#173c2d]"><header className="bg-white border-b border-[#e8efeb] px-5 py-4"><div className="max-w-6xl mx-auto flex items-center justify-between"><img src="https://i.imgur.com/HqvEmQF.png" className="h-8" /><button onClick={onLogout} className="flex items-center gap-2 text-sm font-semibold text-gray-600"><LogOut size={16}/> Sair</button></div></header>
 <main className="max-w-6xl mx-auto p-4 sm:p-7">
 <section className="bg-[#12382c] text-white rounded-2xl p-4 sm:p-5 shadow-[0_8px_28px_rgba(18,56,44,0.12)]"><p className="text-sm font-medium text-emerald-100">Seu link de indicação</p><div className="flex flex-col sm:flex-row gap-3 mt-2"><div className="flex-1 bg-white/10 rounded-xl px-4 py-3 text-sm break-all">{link}</div><button onClick={copy} className="bg-emerald-500 text-[#0b2b20] font-bold rounded-xl px-5 py-3 flex items-center justify-center gap-2"><Copy size={17}/>{copied?'Copiado!':'Copiar link'}</button></div><p className="text-xs text-emerald-100/65 mt-3">As visualizações começam a ser contabilizadas quando alguém acessa este link.</p></section>
 <div className="grid grid-cols-2 gap-3 sm:gap-4 mt-4">{cards.map(([label,value,Icon]:any)=><div key={label} className="bg-white rounded-2xl p-4 sm:p-5 min-h-[132px] shadow-[0_4px_18px_rgba(25,55,43,0.07)] flex flex-col justify-between"><Icon size={20} className="text-emerald-600"/><div><p className="text-xs sm:text-sm text-gray-500">{label}</p><p className="text-xl sm:text-2xl font-bold mt-1">{value}</p></div></div>)}</div>
 <section className="bg-white rounded-2xl mt-4 shadow-[0_4px_18px_rgba(25,55,43,0.07)] overflow-hidden"><div className="p-5 border-b border-[#edf2ef]"><h2 className="font-bold">Indicações recentes</h2></div><div className="divide-y divide-[#edf2ef]">{d.clients?.length?d.clients.map((c:any,i:number)=><div key={i} className="p-4 flex justify-between gap-4"><div><p className="font-semibold">{c.name}</p><p className="text-xs text-gray-500">{c.email}</p></div><div className="text-right"><p className={c.status==='converted'?'text-emerald-600 font-bold':'text-amber-600 font-bold'}>{c.status==='converted'?'Assinado':'Cadastrado'}</p>{c.commissionValue!=null&&<p className="text-xs text-gray-500">R$ {Number(c.commissionValue).toFixed(2).replace('.',',')}</p>}</div></div>):<p className="p-6 text-sm text-gray-500">Nenhuma indicação ainda.</p>}</div></section></main></div>
}