import React,{useEffect,useState} from 'react';
import {Copy,Eye,Users,UserCheck,DollarSign,LogOut} from 'lucide-react';
import {representativeService} from '../../services/representativeService';
export function RepresentativeDashboard({onLogout}:{onLogout:()=>void}){
 const [d,setD]=useState<any>(null); const [copied,setCopied]=useState(false);
 useEffect(()=>{representativeService.dashboard().then(setD).catch(()=>setD(false));},[]);
 if(!d)return <div className="min-h-screen grid place-items-center bg-[#f7faf8] text-[#12382c]">{d===false?'Não foi possível carregar o painel.':'Carregando...'}</div>;
 const link=`${location.origin}/representante/${d.slug}`;
 const copy=async()=>{await navigator.clipboard.writeText(link);setCopied(true);setTimeout(()=>setCopied(false),1600)};
 const cards=[['Views',d.views,Eye],['Cadastros',d.leads,Users],['Clientes assinados',d.clients,UserCheck],['Comissão','R$ '+Number(d.commissionTotal||0).toFixed(2).replace('.',','),DollarSign]];
 return <div className="min-h-screen bg-[#f7faf8] text-[#173c2d]"><header className="bg-white border-b px-5 py-4"><div className="max-w-6xl mx-auto flex items-center justify-between"><img src="https://i.imgur.com/HqvEmQF.png" className="h-8" /><button onClick={onLogout} className="flex items-center gap-2 text-sm font-semibold text-gray-600"><LogOut size={16}/> Sair</button></div></header>
 <main className="max-w-6xl mx-auto p-5 sm:p-8"><p className="text-sm text-gray-500">Painel do representante</p><h1 className="text-2xl font-bold mt-1">Olá, {d.name}</h1><p className="text-sm text-gray-500 mt-1">Sua comissão atual é de <b>{Number(d.commissionPercent)}%</b> por cliente convertido.</p>
 <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-7">{cards.map(([label,value,Icon]:any)=><div key={label} className="bg-white rounded-2xl border p-5 shadow-sm"><Icon size={20} className="text-emerald-600"/><p className="text-sm text-gray-500 mt-4">{label}</p><p className="text-2xl font-bold mt-1">{value}</p></div>)}</div>
 <section className="bg-[#12382c] text-white rounded-2xl p-5 sm:p-6 mt-6"><p className="text-sm text-emerald-200">Seu link de indicação</p><div className="flex flex-col sm:flex-row gap-3 mt-2"><div className="flex-1 bg-white/10 border border-white/15 rounded-xl px-4 py-3 text-sm break-all">{link}</div><button onClick={copy} className="bg-emerald-500 text-[#0b2b20] font-bold rounded-xl px-5 py-3 flex items-center justify-center gap-2"><Copy size={17}/>{copied?'Copiado!':'Copiar link'}</button></div><p className="text-xs text-emerald-100/70 mt-3">As visualizações começam a ser contabilizadas quando alguém acessa este link.</p></section>
 <section className="bg-white rounded-2xl border mt-6 overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold">Indicações recentes</h2></div><div className="divide-y">{d.clients?.length?d.clients.map((c:any,i:number)=><div key={i} className="p-4 flex justify-between gap-4"><div><p className="font-semibold">{c.name}</p><p className="text-xs text-gray-500">{c.email}</p></div><div className="text-right"><p className={c.status==='converted'?'text-emerald-600 font-bold':'text-amber-600 font-bold'}>{c.status==='converted'?'Assinado':'Cadastrado'}</p>{c.commissionValue!=null&&<p className="text-xs text-gray-500">R$ {Number(c.commissionValue).toFixed(2).replace('.',',')}</p>}</div></div>):<p className="p-6 text-sm text-gray-500">Nenhuma indicação ainda.</p>}</div></section></main></div>
}