import React,{useEffect,useMemo,useState} from 'react';
import {Banknote,CircleDollarSign,Clock3,TrendingUp,RefreshCw,Search,ReceiptText,WalletCards,AlertCircle} from 'lucide-react';
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const paid=(s:any)=>['CONFIRMED','RECEIVED','RECEIVED_IN_CASH'].includes(String(s||'').toUpperCase());
const pending=(s:any)=>['PENDING','AWAITING_RISK_ANALYSIS'].includes(String(s||'').toUpperCase());
const label=(s:any)=>{const v=String(s||'PENDING').toUpperCase();if(paid(v))return'Recebido';if(v==='OVERDUE')return'Vencido';if(v==='REFUNDED')return'Estornado';if(v==='CANCELED'||v==='CANCELLED')return'Cancelado';return'Pendente'};
export function ManagerBillingView({mode}:{mode:'financeiro'|'faturamento'|'pagamentos'}){
 const[data,setData]=useState<any>({invoices:[],plans:[],mrr:0}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/admin/billing');const d=await r.json();if(!r.ok)throw new Error(d.error||'Erro');setData(d)}catch{setError('Não foi possível carregar os dados financeiros.')}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const inv:any[]=data.invoices||[];const now=new Date();const month=now.getMonth(),year=now.getFullYear();
 const stats=useMemo(()=>{const received=inv.filter(x=>paid(x.status)).reduce((a,x)=>a+Number(x.netValue??x.value??0),0);const monthReceived=inv.filter(x=>paid(x.status)&&x.paidAt&&new Date(x.paidAt).getMonth()===month&&new Date(x.paidAt).getFullYear()===year).reduce((a,x)=>a+Number(x.netValue??x.value??0),0);const pend=inv.filter(x=>pending(x.status)).reduce((a,x)=>a+Number(x.value||0),0);const overdue=inv.filter(x=>String(x.status).toUpperCase()==='OVERDUE'||(pending(x.status)&&x.dueDate&&new Date(x.dueDate)<new Date(new Date().toDateString()))).reduce((a,x)=>a+Number(x.value||0),0);return{received,monthReceived,pend,overdue}},[inv,month,year]);
 const filtered=inv.filter(x=>[x.customerName,x.customerEmail,x.paymentId,x.planId,x.status,x.billingType].join(' ').toLowerCase().includes(q.toLowerCase()));
 const title=mode==='financeiro'?'Financeiro':mode==='faturamento'?'Faturamento':'Pagamentos';const subtitle=mode==='financeiro'?'Visão consolidada da receita e saúde financeira.':mode==='faturamento'?'Acompanhe cobranças, vencimentos e receita recorrente.':'Histórico real das cobranças processadas pela plataforma.';
 const cards=[{l:'MRR contratado',v:money(data.mrr),h:'assinaturas ativas',i:TrendingUp},{l:'Recebido no mês',v:money(stats.monthReceived),h:'valor líquido registrado',i:CircleDollarSign},{l:'A receber',v:money(stats.pend),h:'cobranças pendentes',i:Clock3},{l:'Em atraso',v:money(stats.overdue),h:'vencido ou pendente vencido',i:AlertCircle}];
 return <main className="min-h-full overflow-y-auto bg-[#f6f9f7] px-4 py-5 sm:px-7 sm:py-7 pb-[calc(6rem+env(safe-area-inset-bottom))] lg:pb-8"><div className="mx-auto max-w-7xl"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-[11px] font-black uppercase tracking-[.16em] text-emerald-700"><WalletCards size={15}/>Gestão financeira</div><h1 className="text-2xl font-black text-[#17251e] sm:text-3xl">{title}</h1><p className="mt-1 text-sm text-[#718078]">{subtitle}</p></div><button onClick={load} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-[#315044] shadow-sm"><RefreshCw size={16}/>Atualizar</button></header>
 <div className="mt-6 grid grid-cols-2 gap-3 xl:grid-cols-4">{cards.map(({l,v,h,i:Icon})=><article key={l} className="rounded-3xl bg-white p-4 shadow-[0_10px_35px_rgba(24,60,44,.05)] sm:p-5"><div className="flex justify-between gap-2"><div><p className="text-xs font-semibold text-[#809087]">{l}</p><p className="mt-3 text-xl font-black text-[#173c2d] sm:text-2xl">{loading?'—':v}</p></div><span className="grid h-9 w-9 place-items-center rounded-2xl bg-[#edf7f2] text-emerald-700"><Icon size={17}/></span></div><p className="mt-2 text-[11px] text-[#94a099]">{h}</p></article>)}</div>
 {mode==='faturamento'&&<section className="mt-5 rounded-3xl bg-white p-5 shadow-[0_10px_35px_rgba(24,60,44,.05)]"><h2 className="font-black text-[#173c2d]">Receita recorrente por plano</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{(data.plans||[]).map((p:any)=><div key={p.id} className="rounded-2xl bg-[#f5f8f6] p-4"><div className="flex items-center justify-between"><p className="text-sm font-black">{p.name}</p><ReceiptText size={16} className="text-emerald-700"/></div><p className="mt-3 text-xl font-black text-[#173c2d]">{money(Number(p.monthlyPrice)*Number(p.subscribers))}</p><p className="mt-1 text-xs text-[#84928b]">{p.subscribers} assinatura{p.subscribers===1?'':'s'} ativa{p.subscribers===1?'':'s'}</p></div>)}</div></section>}
 <div className="relative mt-5"><Search size={17} className="absolute left-4 top-3.5 text-[#8a9891]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente, cobrança, plano ou status..." className="w-full rounded-2xl bg-white py-3 pl-11 pr-4 text-sm outline-none shadow-[0_6px_24px_rgba(25,55,43,.04)]"/></div>
 <section className="mt-4 overflow-hidden rounded-3xl bg-white shadow-[0_10px_35px_rgba(24,60,44,.05)]">{error?<div className="p-10 text-center text-sm font-semibold text-red-600">{error}</div>:loading?<div className="p-12 text-center text-sm text-[#829087]">Carregando movimentações...</div>:!filtered.length?<div className="p-12 text-center text-sm text-[#829087]">Nenhuma cobrança encontrada.</div>:<div className="divide-y divide-[#f0f4f2]">{filtered.map(x=><article key={x.id} className="grid gap-3 px-5 py-4 hover:bg-[#fbfcfb] sm:px-6 lg:grid-cols-[1.35fr_.55fr_.65fr_.65fr_.7fr] lg:items-center"><div className="min-w-0"><p className="truncate text-sm font-bold text-[#263c32]">{x.customerName||'Cliente'}</p><p className="truncate text-xs text-[#8a9891]">{x.customerEmail}</p></div><div><p className="text-[10px] font-bold uppercase text-[#9aa59f]">Plano</p><p className="text-xs font-black uppercase text-[#40574d]">{x.planId}</p></div><div><p className="text-[10px] font-bold uppercase text-[#9aa59f]">Valor</p><p className="text-sm font-black text-[#274438]">{money(x.value)}</p></div><div><p className="text-[10px] font-bold uppercase text-[#9aa59f]">Vencimento</p><p className="text-xs font-semibold text-[#52645b]">{x.dueDate?new Date(x.dueDate).toLocaleDateString('pt-BR'):'—'}</p></div><div className="lg:text-right"><span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-black ${paid(x.status)?'bg-emerald-50 text-emerald-700':label(x.status)==='Vencido'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{label(x.status)}</span><p className="mt-1 text-[10px] text-[#98a39d]">{x.billingType||'PIX'} • {x.gateway||'ASAAS'}</p></div></article>)}</div>}</section>
 </div></main>
}