import React,{useEffect,useMemo,useState} from 'react';
import {Users,CreditCard,Activity,UserCheck,ArrowUpRight,RefreshCw,Clock3,ShieldCheck} from 'lucide-react';

export function ManagerDashboard({onNavigate}:{onNavigate:(tab:string)=>void}){
 const[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/admin/subscriptions');const d=await r.json();if(!r.ok)throw new Error(d.error||'Erro');setRows(d.subscriptions||[])}catch{setError('Não foi possível carregar os dados gerenciais.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const stats=useMemo(()=>{const active=rows.filter(x=>String(x.subscription_status||x.user_status).toLowerCase()==='active').length;return{total:rows.length,active,campaigns:rows.reduce((a,x)=>a+Number(x.campaigns||0),0),events:rows.reduce((a,x)=>a+Number(x.monthly_events||0),0)}},[rows]);
 const recent=useMemo(()=>[...rows].sort((a,b)=>new Date(b.created_at||b.updated_at||0).getTime()-new Date(a.created_at||a.updated_at||0).getTime()).slice(0,5),[rows]);
 const cards=[{label:'Assinantes',value:stats.total,helper:'clientes cadastrados',icon:Users},{label:'Assinaturas ativas',value:stats.active,helper:stats.total?Math.round(stats.active/stats.total*100)+'% da base':'base iniciando',icon:CreditCard},{label:'Divulgações',value:stats.campaigns,helper:'campanhas criadas',icon:Activity},{label:'Eventos / 30 dias',value:stats.events,helper:'atividade recente',icon:Clock3}];
 return <main className="min-h-full overflow-y-auto bg-[#f6f9f7] px-4 py-5 sm:px-7 sm:py-7 pb-[calc(6rem+env(safe-area-inset-bottom))] lg:pb-8"><div className="mx-auto max-w-7xl">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-[11px] font-black uppercase tracking-[.16em] text-emerald-700"><ShieldCheck size={15}/>Painel do Gerente</div><h1 className="text-2xl font-black tracking-tight text-[#17251e] sm:text-3xl">Visão geral</h1><p className="mt-1 max-w-xl text-sm text-[#718078]">Acompanhe a operação da Groply e acesse rapidamente as áreas de gestão.</p></div><button onClick={load} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-[#315044] shadow-sm hover:bg-[#edf4f0]"><RefreshCw size={16}/>Atualizar</button></header>
  <div className="mt-6 grid grid-cols-2 gap-3 xl:grid-cols-4">{cards.map(({label,value,helper,icon:Icon})=><article key={label} className="rounded-3xl border border-white bg-white p-4 shadow-[0_10px_35px_rgba(24,60,44,.05)] sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-[#809087]">{label}</p><p className="mt-3 text-3xl font-black tracking-tight text-[#173c2d]">{loading?'—':value}</p></div><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#edf7f2] text-emerald-700"><Icon size={18}/></span></div><p className="mt-2 text-[11px] font-medium text-[#94a099]">{helper}</p></article>)}</div>
  {error&&<div className="mt-5 rounded-2xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
  <div className="mt-5 grid gap-5 xl:grid-cols-[1.55fr_.85fr]"><section className="overflow-hidden rounded-3xl bg-white shadow-[0_10px_35px_rgba(24,60,44,.05)]"><div className="flex items-center justify-between border-b border-[#eef3f0] px-5 py-5 sm:px-6"><div><h2 className="font-black text-[#173c2d]">Assinantes recentes</h2><p className="mt-1 text-xs text-[#87958e]">Visão rápida da base de clientes</p></div><button onClick={()=>onNavigate('assinantes')} className="flex items-center gap-1 text-xs font-black text-emerald-700">Ver todos <ArrowUpRight size={14}/></button></div>{loading?<div className="p-10 text-center text-sm text-[#8b9891]">Carregando...</div>:recent.length?<div className="divide-y divide-[#f0f4f2]">{recent.map(x=><div key={x.user_id} className="flex items-center justify-between gap-4 px-5 py-4 sm:px-6"><div className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#e9f5ef] text-sm font-black text-emerald-800">{String(x.name||'C').slice(0,1).toUpperCase()}</span><div className="min-w-0"><p className="truncate text-sm font-bold text-[#263c32]">{x.name||'Cliente'}</p><p className="truncate text-xs text-[#8a9891]">{x.email||'Sem e-mail'}</p></div></div><div className="text-right"><p className="text-xs font-black uppercase text-[#40574d]">{x.plan_id||'—'}</p><p className={"mt-1 text-[10px] font-bold "+(String(x.subscription_status||x.user_status).toLowerCase()==='active'?'text-emerald-700':'text-amber-700')}>{String(x.subscription_status||x.user_status||'pendente').toLowerCase()==='active'?'Ativo':(x.subscription_status||x.user_status||'Pendente')}</p></div></div>)}</div>:<div className="p-10 text-center text-sm text-[#8b9891]">Nenhum assinante ainda.</div>}</section>
  <aside className="rounded-3xl bg-[#153b2f] p-5 text-white shadow-[0_12px_40px_rgba(18,56,44,.16)] sm:p-6"><p className="text-[11px] font-black uppercase tracking-[.14em] text-emerald-300">Acesso rápido</p><h2 className="mt-2 text-xl font-black">Gestão sem complicação.</h2><p className="mt-2 text-sm leading-6 text-emerald-50/70">Entre direto nas áreas administrativas mais usadas.</p><div className="mt-6 space-y-2"><button onClick={()=>onNavigate('assinantes')} className="flex w-full items-center justify-between rounded-2xl bg-white/10 px-4 py-3 text-left text-sm font-bold hover:bg-white/15"><span className="flex items-center gap-2"><Users size={16}/>Assinantes</span><ArrowUpRight size={15}/></button><button onClick={()=>onNavigate('representantes')} className="flex w-full items-center justify-between rounded-2xl bg-white/10 px-4 py-3 text-left text-sm font-bold hover:bg-white/15"><span className="flex items-center gap-2"><UserCheck size={16}/>Representantes</span><ArrowUpRight size={15}/></button></div></aside></div>
 </div></main>
}