import React,{useEffect,useMemo,useState} from 'react';
import {Plus,Copy,Users,Eye,UserCheck,Percent,Link2,RefreshCw} from 'lucide-react';
import {representativeService} from '../../services/representativeService';

const inputClass='w-full rounded-xl bg-[#f5f8f6] px-3.5 py-3 text-sm text-[#173c2d] outline-none ring-1 ring-transparent focus:bg-white focus:ring-emerald-200 transition';
export function RepresentativesAdminView(){
 const [items,setItems]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const [form,setForm]=useState({name:'',email:'',password:'',slug:'',commissionPercent:10});
 const load=()=>{setLoading(true);setError('');representativeService.list().then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false))}; useEffect(load,[]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await representativeService.create(form);setForm({name:'',email:'',password:'',slug:'',commissionPercent:10});load()}catch(e:any){setError(e.message)}};
 const totals=useMemo(()=>({views:items.reduce((a,r)=>a+Number(r.views||0),0),clients:items.reduce((a,r)=>a+Number(r.clients||0),0),active:items.filter(r=>Boolean(r.isActive)).length}),[items]);
 const stats=[{label:'Representantes',value:items.length,icon:Users},{label:'Ativos',value:totals.active,icon:UserCheck},{label:'Visualizações',value:totals.views,icon:Eye},{label:'Clientes gerados',value:totals.clients,icon:Link2}];
 return <main className="flex-1 overflow-y-auto bg-[#f7faf8] px-4 py-5 sm:px-7 sm:py-7"><div className="mx-auto max-w-7xl">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-emerald-700"><span className="h-2 w-2 rounded-full bg-emerald-500"/>Programa comercial</div><h1 className="text-2xl font-black tracking-tight text-[#17251e] sm:text-3xl">Representantes</h1><p className="mt-1 text-sm text-[#708078]">Gerencie acessos, links de indicação e comissões em um só lugar.</p></div><button onClick={load} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-[#315044] shadow-sm hover:bg-[#f1f6f3]"><RefreshCw size={16}/>Atualizar</button></div>
  <div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map(({label,value,icon:Icon})=><div key={label} className="rounded-2xl bg-white p-4 shadow-[0_8px_30px_rgba(25,55,43,.05)] sm:p-5"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-[#809087]">{label}</span><span className="grid h-8 w-8 place-items-center rounded-xl bg-[#edf7f2] text-emerald-700"><Icon size={16}/></span></div><p className="mt-3 text-2xl font-black text-[#173c2d]">{value}</p></div>)}</div>
  <section className="mt-5 rounded-3xl bg-white p-5 shadow-[0_8px_35px_rgba(25,55,43,.05)] sm:p-6"><div className="mb-5"><h2 className="text-base font-black text-[#173c2d]">Novo representante</h2><p className="mt-1 text-xs text-[#829087]">O acesso é criado na hora e o link fica pronto para compartilhar.</p></div><form onSubmit={create} className="grid gap-3 lg:grid-cols-[1.1fr_1.2fr_1fr_1fr_.8fr]"><input required placeholder="Nome completo" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className={inputClass}/><input required type="email" placeholder="E-mail de acesso" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className={inputClass}/><input required type="password" placeholder="Senha inicial" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className={inputClass}/><div><input required placeholder="nome-do-representante" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} className={inputClass}/><p className="mt-1 px-1 text-[10px] text-[#94a099]">/representante/{form.slug||'nome'}</p></div><div className="flex gap-2"><div className="relative w-24"><input required type="number" min="0" max="100" step=".01" value={form.commissionPercent} onChange={e=>setForm({...form,commissionPercent:Number(e.target.value)})} className={inputClass+' pr-7'}/><Percent size={13} className="absolute right-3 top-3.5 text-[#7d8d84]"/></div><button className="flex flex-1 items-center justify-center gap-1.5 rounded-xl bg-[#12382c] px-4 text-sm font-bold text-white hover:bg-[#194c3b]"><Plus size={16}/>Criar</button></div></form>{error&&<p className="mt-3 text-sm font-semibold text-red-600">{error}</p>}</section>
  <section className="mt-5 overflow-hidden rounded-3xl bg-white shadow-[0_8px_35px_rgba(25,55,43,.05)]"><div className="flex items-center justify-between px-5 py-5 sm:px-6"><div><h2 className="font-black text-[#173c2d]">Equipe de representantes</h2><p className="mt-1 text-xs text-[#829087]">{items.length} acesso{items.length===1?'':'s'} cadastrado{items.length===1?'':'s'}</p></div></div>
  {loading?<div className="px-6 py-12 text-center text-sm text-[#829087]">Carregando representantes...</div>:!items.length?<div className="px-6 py-12 text-center text-sm text-[#829087]">Nenhum representante cadastrado.</div>:<div className="divide-y divide-[#f0f4f2]">{items.map(r=><div key={r.id} className="grid gap-4 px-5 py-4 transition hover:bg-[#fbfcfb] sm:px-6 lg:grid-cols-[1.4fr_.7fr_.55fr_.55fr_1.3fr] lg:items-center"><div className="min-w-0"><div className="flex items-center gap-2"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#e9f5ef] text-sm font-black text-emerald-800">{String(r.name||'R').slice(0,1).toUpperCase()}</span><div className="min-w-0"><p className="truncate font-bold text-[#243b31]">{r.name}</p><p className="truncate text-xs text-[#89968f]">{r.email}</p></div></div></div><div><span className="text-[10px] font-bold uppercase tracking-wider text-[#9aa59f] lg:hidden">Comissão</span><div className="mt-1 flex items-center gap-1 lg:mt-0"><input type="number" defaultValue={r.commissionPercent} className="w-16 rounded-lg bg-[#f4f7f5] p-2 text-center text-sm font-bold outline-none focus:ring-1 focus:ring-emerald-200" onBlur={async e=>{await representativeService.update(r.id,{commissionPercent:Number(e.target.value),isActive:Boolean(r.isActive)});load()}}/><span className="text-sm font-bold text-[#617068]">%</span></div></div><div><span className="text-[10px] font-bold uppercase text-[#9aa59f] lg:hidden">Views</span><p className="font-black text-[#314b40]">{r.views}</p></div><div><span className="text-[10px] font-bold uppercase text-[#9aa59f] lg:hidden">Clientes</span><p className="font-black text-[#314b40]">{r.clients}</p></div><button onClick={()=>navigator.clipboard.writeText(location.origin+'/representante/'+r.slug)} className="flex min-w-0 items-center gap-2 rounded-xl bg-[#f3f7f5] px-3 py-2.5 text-left text-xs font-bold text-emerald-800 hover:bg-[#eaf4ef]"><Copy size={14} className="shrink-0"/><span className="truncate">/representante/{r.slug}</span></button></div>)}</div>}</section>
 </div></main>
}