import React,{useEffect,useState} from 'react';
import {Plus,Copy,Users} from 'lucide-react'; import {representativeService} from '../../services/representativeService';
export function RepresentativesAdminView(){
 const [items,setItems]=useState<any[]>([]),[error,setError]=useState(''); const [form,setForm]=useState({name:'',email:'',password:'',slug:'',commissionPercent:10});
 const load=()=>representativeService.list().then(setItems).catch(e=>setError(e.message)); useEffect(load,[]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await representativeService.create(form);setForm({name:'',email:'',password:'',slug:'',commissionPercent:10});load();}catch(e:any){setError(e.message)}};
 return <div className="flex-1 overflow-y-auto p-4 sm:p-7 bg-[#f7faf8]"><div className="max-w-6xl mx-auto"><div className="flex items-center gap-3"><Users className="text-emerald-600"/><div><h1 className="text-2xl font-bold text-[#173c2d]">Representantes</h1><p className="text-sm text-gray-500">Crie acessos, links e defina a comissão.</p></div></div>
 <form onSubmit={create} className="bg-white border rounded-2xl p-5 mt-6 grid md:grid-cols-5 gap-3"><input required placeholder="Nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="border rounded-xl px-3 py-2.5"/><input required type="email" placeholder="E-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="border rounded-xl px-3 py-2.5"/><input required type="password" placeholder="Senha" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="border rounded-xl px-3 py-2.5"/><div><input required placeholder="link-exemplo" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} className="w-full border rounded-xl px-3 py-2.5"/><p className="text-[10px] text-gray-400 mt-1">/representante/{form.slug||'nome'}</p></div><div className="flex gap-2"><input required type="number" min="0" max="100" step=".01" value={form.commissionPercent} onChange={e=>setForm({...form,commissionPercent:Number(e.target.value)})} className="w-20 border rounded-xl px-3 py-2.5"/><button className="flex-1 bg-[#12382c] text-white rounded-xl font-bold flex items-center justify-center gap-1"><Plus size={16}/>Criar</button></div></form>{error&&<p className="text-red-600 text-sm mt-3">{error}</p>}
 <div className="bg-white border rounded-2xl mt-5 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 text-gray-500"><tr><th className="p-4 text-left">Representante</th><th className="p-4">Comissão</th><th className="p-4">Views</th><th className="p-4">Clientes</th><th className="p-4 text-left">Link</th></tr></thead><tbody>{items.map(r=><tr key={r.id} className="border-t"><td className="p-4"><b>{r.name}</b><div className="text-xs text-gray-500">{r.email}</div></td><td className="p-4 text-center"><input type="number" defaultValue={r.commissionPercent} className="w-20 border rounded-lg p-2 text-center" onBlur={async e=>{await representativeService.update(r.id,{commissionPercent:Number(e.target.value),isActive:Boolean(r.isActive)});load()}}/>%</td><td className="p-4 text-center">{r.views}</td><td className="p-4 text-center">{r.clients}</td><td className="p-4"><button onClick={()=>navigator.clipboard.writeText(location.origin+'/representante/'+r.slug)} className="flex items-center gap-2 text-emerald-700 font-semibold"><Copy size={14}/>/representante/{r.slug}</button></td></tr>)}</tbody></table></div></div></div>
}