import React,{useEffect,useMemo,useState} from 'react';
import{RefreshCw,CheckCircle2,PauseCircle,CalendarPlus,Search,Users,CreditCard,Activity,Clock3}from'lucide-react';
export const SubscriptionsAdminView=()=>{
 const[rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/admin/subscriptions');const d=await r.json();if(r.status===403){window.location.reload();throw new Error('Sessão administrativa inválida')}if(!r.ok)throw new Error(d.error||'Erro');setRows(d.subscriptions||[])}catch{setError('Não foi possível carregar os assinantes.')}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const act=async(id:number,action:string)=>{const r=await fetch(`/api/admin/subscriptions/${id}/action`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});if(r.ok)await load()};
 const list=rows.filter(x=>[x.name,x.email,x.plan_id,x.subscription_status,x.user_status].join(' ').toLowerCase().includes(q.toLowerCase()));
 const stats=useMemo(()=>({total:rows.length,active:rows.filter(x=>String(x.subscription_status||x.user_status).toLowerCase()==='active').length,campaigns:rows.reduce((a,x)=>a+Number(x.campaigns||0),0),events:rows.reduce((a,x)=>a+Number(x.monthly_events||0),0)}),[rows]);
 const badge=(x:any)=>{const v=String(x.subscription_status||x.user_status||'pendente').toLowerCase();const ok=v==='active';return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-bold ${ok?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}><span className={`h-1.5 w-1.5 rounded-full ${ok?'bg-emerald-500':'bg-amber-500'}`}/>{ok?'Ativo':v}</span>};
 const cards=[['Assinantes',stats.total,Users],['Ativos',stats.active,CreditCard],['Divulgações',stats.campaigns,Activity],['Eventos / 30 dias',stats.events,Clock3]];
 return <main className="flex-1 overflow-y-auto bg-[#f7faf8] px-4 py-5 sm:px-7 sm:py-7"><div className="mx-auto max-w-7xl">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-emerald-700"><span className="h-2 w-2 rounded-full bg-emerald-500"/>Gestão de clientes</div><h1 className="text-2xl font-black tracking-tight text-[#17251e] sm:text-3xl">Assinaturas</h1><p className="mt-1 text-sm text-[#708078]">Acompanhe planos, acessos, renovação e atividade dos clientes.</p></div><button onClick={load} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-[#315044] shadow-sm hover:bg-[#f1f6f3]"><RefreshCw size={16}/>Atualizar</button></div>
  <div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(([label,value,Icon]:any)=><div key={label} className="rounded-2xl bg-white p-4 shadow-[0_8px_30px_rgba(25,55,43,.05)] sm:p-5"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-[#809087]">{label}</span><span className="grid h-8 w-8 place-items-center rounded-xl bg-[#edf7f2] text-emerald-700"><Icon size={16}/></span></div><p className="mt-3 text-2xl font-black text-[#173c2d]">{value}</p></div>)}</div>
  <div className="relative mt-5"><Search size={17} className="absolute left-4 top-3.5 text-[#8a9891]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por cliente, e-mail, plano ou status..." className="w-full rounded-2xl bg-white py-3 pl-11 pr-4 text-sm outline-none shadow-[0_6px_24px_rgba(25,55,43,.04)] focus:ring-1 focus:ring-emerald-200"/></div>
  <section className="mt-4 overflow-hidden rounded-3xl bg-white shadow-[0_8px_35px_rgba(25,55,43,.05)]">{loading?<div className="p-12 text-center text-sm text-[#829087]">Carregando assinaturas...</div>:error?<div className="p-10 text-center"><p className="text-sm font-semibold text-red-600">{error}</p><button onClick={load} className="mt-3 rounded-xl bg-[#f2f6f4] px-4 py-2 text-sm font-bold text-[#315044]">Tentar novamente</button></div>:!list.length?<div className="p-12 text-center text-sm text-[#829087]">Nenhum assinante encontrado.</div>:<div className="divide-y divide-[#f0f4f2]">{list.map(x=><article key={x.user_id} className="grid gap-4 px-5 py-4 transition hover:bg-[#fbfcfb] sm:px-6 lg:grid-cols-[1.45fr_.55fr_.65fr_.8fr_1.15fr_.8fr] lg:items-center"><div className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#e9f5ef] text-sm font-black text-emerald-800">{String(x.name||'C').slice(0,1).toUpperCase()}</span><div className="min-w-0"><p className="truncate font-bold text-[#243b31]">{x.name}</p><p className="truncate text-xs text-[#89968f]">{x.email}</p></div></div><div><span className="text-[10px] font-bold uppercase text-[#9aa59f] lg:hidden">Plano</span><p className="text-sm font-black uppercase text-[#344d42]">{x.plan_id||'—'}</p></div><div>{badge(x)}</div><div><span className="text-[10px] font-bold uppercase text-[#9aa59f] lg:hidden">Renovação</span><p className="text-sm font-semibold text-[#52645b]">{x.next_due_date?new Date(x.next_due_date).toLocaleDateString('pt-BR'):'—'}</p></div><div><span className="text-[10px] font-bold uppercase text-[#9aa59f] lg:hidden">Uso</span><p className="text-xs font-semibold text-[#52645b]">{x.campaigns||0} divulgações</p><p className="mt-0.5 text-[11px] text-[#95a099]">{x.monthly_events||0} eventos nos últimos 30 dias</p></div><div className="flex gap-1.5"><button onClick={()=>act(x.user_id,'approve')} className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-50 text-emerald-700 hover:bg-emerald-100" title="Aprovar"><CheckCircle2 size={16}/></button><button onClick={()=>act(x.user_id,'renew')} className="grid h-9 w-9 place-items-center rounded-xl bg-[#f2f6f4] text-[#456056] hover:bg-[#e9f0ec]" title="Renovar"><CalendarPlus size={16}/></button><button onClick={()=>act(x.user_id,'suspend')} className="grid h-9 w-9 place-items-center rounded-xl bg-amber-50 text-amber-700 hover:bg-amber-100" title="Suspender"><PauseCircle size={16}/></button></div></article>)}</div>}</section>
 </div></main>
}
