import React,{useEffect,useState} from 'react';import{RefreshCw,CheckCircle2,PauseCircle,CalendarPlus,Search}from'lucide-react';
export const SubscriptionsAdminView=()=>{const[rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
const headers=()=>({});const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/admin/subscriptions',{headers:headers()});const d=await r.json();if(r.status===403){window.location.reload();throw new Error('SessÃ£o administrativa invÃ¡lida');}if(!r.ok)throw new Error(d.error||'Erro');setRows(d.subscriptions||[])}catch{setError('NÃ£o foi possÃ­vel carregar os assinantes.')}finally{setLoading(false)}};useEffect(()=>{load()},[]);
const act=async(id:number,action:string)=>{const r=await fetch(`/api/admin/subscriptions/${id}/action`,{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({action})});if(r.ok)await load()};
const list=rows.filter(x=>[x.name,x.email,x.plan_id,x.subscription_status,x.user_status].join(' ').toLowerCase().includes(q.toLowerCase()));
const badge=(x:any)=>{const v=x.subscription_status||x.user_status||'pendente';return <span className="inline-flex px-2.5 py-1 rounded-full bg-[#eef4f1] text-[#244438] text-xs font-bold">{v}</span>};
return <main className="p-4 sm:p-7 max-w-7xl mx-auto pb-28 lg:pb-8"><div className="flex items-start justify-between gap-3 mb-5"><div><h1 className="text-2xl sm:text-3xl font-black text-[#17251e]">Assinantes</h1><p className="text-sm text-gray-500 mt-1">Assinaturas, acesso e uso do Grolpy.</p></div><button onClick={load} className="shrink-0 w-11 h-11 sm:w-auto sm:px-4 border bg-white rounded-xl flex items-center justify-center gap-2"><RefreshCw size={17}/><span className="hidden sm:inline">Atualizar</span></button></div>
<div className="relative mb-4"><Search size={17} className="absolute left-3.5 top-3.5 text-gray-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar assinante..." className="w-full pl-10 pr-4 py-3 bg-white border rounded-xl text-sm"/></div>
{loading?<div className="bg-white border rounded-2xl p-8 text-center text-sm text-gray-500">Carregando assinantes...</div>:error?<div className="bg-white border rounded-2xl p-6 text-center"><p className="text-sm text-red-600">{error}</p><button onClick={load} className="mt-3 px-4 py-2 border rounded-xl font-bold text-sm">Tentar novamente</button></div>:!list.length?<div className="bg-white border rounded-2xl p-8 text-center text-sm text-gray-500">Nenhum assinante encontrado.</div>:<>
<div className="grid gap-3 md:hidden">{list.map(x=><section key={x.user_id} className="bg-white border rounded-2xl p-4"><div className="flex justify-between gap-3"><div className="min-w-0"><h3 className="font-black truncate">{x.name}</h3><p className="text-xs text-gray-500 truncate">{x.email}</p></div>{badge(x)}</div><div className="grid grid-cols-2 gap-3 mt-4 text-sm"><div><span className="text-xs text-gray-500">Plano</span><p className="font-bold uppercase">{x.plan_id||'â€”'}</p></div><div><span className="text-xs text-gray-500">RenovaÃ§Ã£o</span><p className="font-bold">{x.next_due_date?new Date(x.next_due_date).toLocaleDateString('pt-BR'):'â€”'}</p></div><div className="col-span-2"><span className="text-xs text-gray-500">Uso</span><p>{x.campaigns||0} divulgaÃ§Ãµes Â· {x.monthly_events||0} eventos nos Ãºltimos 30 dias</p></div></div><div className="grid grid-cols-3 gap-2 mt-4 pt-4 border-t"><button onClick={()=>act(x.user_id,'approve')} className="py-2.5 border rounded-xl text-xs font-bold flex items-center justify-center gap-1"><CheckCircle2 size={15}/>Aprovar</button><button onClick={()=>act(x.user_id,'renew')} className="py-2.5 border rounded-xl text-xs font-bold flex items-center justify-center gap-1"><CalendarPlus size={15}/>Renovar</button><button onClick={()=>act(x.user_id,'suspend')} className="py-2.5 border rounded-xl text-xs font-bold flex items-center justify-center gap-1"><PauseCircle size={15}/>Suspender</button></div></section>)}</div>
<div className="hidden md:block bg-white border rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 text-left"><tr><th className="p-4">Cliente</th><th>Plano</th><th>Status</th><th>RenovaÃ§Ã£o</th><th>Uso</th><th>AÃ§Ãµes</th></tr></thead><tbody>{list.map(x=><tr key={x.user_id} className="border-t"><td className="p-4"><b>{x.name}</b><div className="text-xs text-gray-500">{x.email}</div></td><td className="uppercase">{x.plan_id||'â€”'}</td><td>{badge(x)}</td><td>{x.next_due_date?new Date(x.next_due_date).toLocaleDateString('pt-BR'):'â€”'}</td><td>{x.campaigns||0} divulgaÃ§Ãµes Â· {x.monthly_events||0} eventos/30d</td><td><div className="flex gap-2"><button onClick={()=>act(x.user_id,'approve')} className="p-2 border rounded-lg" title="Aprovar"><CheckCircle2 size={16}/></button><button onClick={()=>act(x.user_id,'renew')} className="p-2 border rounded-lg" title="Renovar"><CalendarPlus size={16}/></button><button onClick={()=>act(x.user_id,'suspend')} className="p-2 border rounded-lg" title="Suspender"><PauseCircle size={16}/></button></div></td></tr>)}</tbody></table></div></>}</main>};
